// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4_1.Models;

namespace _4_1.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20200920143322_Genre")]
    partial class Genre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_4_1.Models.Genre", b =>
                {
                    b.Property<string>("GenreID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = "A",
                            Name = "Action"
                        },
                        new
                        {
                            GenreID = "C",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreID = "D",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreID = "H",
                            Name = "Horror"
                        },
                        new
                        {
                            GenreID = "M",
                            Name = "Musical"
                        },
                        new
                        {
                            GenreID = "R",
                            Name = "RomCom"
                        },
                        new
                        {
                            GenreID = "S",
                            Name = "SciFi"
                        });
                });

            modelBuilder.Entity("_4_1.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieID");

                    b.HasIndex("GenreID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            GenreID = "D",
                            Name = "Casablanca",
                            Rating = 4,
                            Year = 1942
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = "A",
                            Name = "Wonder Woman",
                            Rating = 5,
                            Year = 2017
                        },
                        new
                        {
                            MovieID = 3,
                            GenreID = "R",
                            Name = "Moonstruck",
                            Rating = 5,
                            Year = 1988
                        });
                });

            modelBuilder.Entity("_4_1.Models.Movie", b =>
                {
                    b.HasOne("_4_1.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
