// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4_1.Models;

namespace _4_1.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_4_1.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "F",
                            Name = "Friend"
                        },
                        new
                        {
                            CategoryID = "W",
                            Name = "Work"
                        },
                        new
                        {
                            CategoryID = "FM",
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("_4_1.Models.Contact", b =>
                {
                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("FName");

                    b.HasIndex("CategoryID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            FName = "Jane",
                            CategoryID = "F",
                            Email = "janedoe@gmail.com",
                            LName = "Doe",
                            PhoneNumber = -9999
                        },
                        new
                        {
                            FName = "John",
                            CategoryID = "W",
                            Email = "johndoe@gmail.com",
                            LName = "Doe",
                            PhoneNumber = -1111
                        },
                        new
                        {
                            FName = "Mary",
                            CategoryID = "FM",
                            Email = "maryjohnson@gmail.com",
                            LName = "Johnson",
                            PhoneNumber = -2222
                        });
                });

            modelBuilder.Entity("_4_1.Models.Contact", b =>
                {
                    b.HasOne("_4_1.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
