// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _8_1.Models;

namespace _8_1.Migrations
{
    [DbContext(typeof(DestinationContext))]
    [Migration("20201014163531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_8_1.Models.Destination", b =>
                {
                    b.Property<string>("TripID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EndDate")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            TripID = "New York",
                            EndDate = 2020,
                            StartDate = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
